'use strict';var initialized=false;navigator.mozSetMessageHandler('activity',function(activity){if(initialized)
return;var tonePlayer=new TonePlayer();var launchType=activity.source.data.toneType;var currentPlayingTone=null;var focusItem=null;var toneList=null;var option=null;var shareState=false;var backFromAddNewTone=false;var addToneState=false;var isPaused=false;initialized=true;if(!localStorage.getItem('isLowMemoryDevice')){navigator.getFeature('hardware.memory').then(function(value){if(value<=256){localStorage.setItem('isLowMemoryDevice',true);}else{localStorage.setItem('isLowMemoryDevice',false);}});}
window.addEventListener('keydown',function(e){if((!document.querySelector('.group-menu'))&&(!document.querySelector('#dialog-screen'))&&(!shareState)&&e.key==='Backspace'){tonePlayer.stop();activity.postError('cancelled');e.preventDefault();}});window.addEventListener('visibilitychange',function(){if(addToneState||shareState){return;}
if((!document.hidden)&&(!backFromAddNewTone)&&(!document.querySelector('.group-menu'))){sendNavigationResetEvent('listReady',{restoreFocus:true});}
backFromAddNewTone=false;});window.addEventListener('largetextenabledchanged',function(){document.body.classList.toggle('large-text',navigator.largeTextEnabled);});document.body.classList.toggle('large-text',navigator.largeTextEnabled);document.getElementById('header').addEventListener('action',function(){tonePlayer.stop();activity.postResult({});});function addNewTone(){addToneState=true;tonePlayer.stop();var pickActivity=new MozActivity({name:'pick',data:{type:'audio/*'}});pickActivity.onsuccess=function(){addToneState=false;var result=pickActivity.result;if(JSON.stringify(result)==='{}'){return;}
var popup=window.open('share.html','share','mozhaidasheet');popup.addEventListener('load',function loaded(){popup.removeEventListener('load',loaded);popup.postMessage(result,window.location.origin);});window.addEventListener('message',function receive(event){window.removeEventListener('message',receive);if(event.origin!==window.location.origin){console.error('Couldn\'t recieve message: origins don\'t match',event.origin,window.location.origin);return;}
var data=event.data;if(data.command!=='save'){return;}
window.customRingtones.get(data.details.toneID).then(function(tone){backFromAddNewTone=true;toneList.add(tone);checkToneListLength();createOptions();sendNavigationResetEvent('listReady',{addNewTone:true,newToneName:tone._name});});});};pickActivity.onerror=function(){addToneState=false;};}
function showShareDialog(){tonePlayer.stop();shareState=true;setTimeout(()=>{option.hide();},100);focusItem.getBlob().then(function(blob){var shareActivity=new MozActivity({name:'share',data:{type:'audio/*',__bug1015513_hide_from_self__:true,number:1,blobs:[blob],filenames:[focusItem.filename],metadata:[{title:focusItem.name}]}});shareActivity.onsuccess=function(e){shareState=false;option.show();sendNavigationResetEvent('listReady',{restoreFocus:true});};shareActivity.onerror=function(e){shareState=false;option.show();sendNavigationResetEvent('listReady',{restoreFocus:true});};});}
function showToast(msgId){var toast={messageL10nId:msgId,useTransition:true};Toaster.showToast(toast);}
function fromListDeleteTone(){tonePlayer.stop();var descKey='delete-desc';window.systemTones.isInUse(focusItem).then(function(arrayList){var paraLength=arrayList.length;if(paraLength){descKey+='-default-'+arrayList[0];}});var dialogConfig={title:{id:'confirmation',args:{}},body:{id:descKey,args:{tone:focusItem.name}},cancel:{name:'Cancel',l10nId:'delete-cancel',priority:1,callback:function(){setTimeout(()=>{option.show();},500);},},confirm:{name:'Delete',l10nId:'delete-confirm',priority:3,callback:function(){showToast('deleted-ringtone');focusItem.remove();window.systemTones.isInUse(focusItem).then(function(inUseAs){toneList.remove(focusItem);inUseAs.forEach(function(toneType){window.systemTones.getDefault(toneType).then(function(tone){window.systemTones.set(toneType,tone);});});checkToneListLength();createOptions();sendNavigationResetEvent('listReady');});},}};var dialog=new ConfirmDialogHelper(dialogConfig);dialog.show(document.getElementById('app-confirmation-dialog'));setTimeout(()=>{option.hide();},5);setTimeout(()=>{document.activeElement&&document.activeElement.blur();},500);}
function ManagerToneList(...args){ToneList.apply(this,args);}
ManagerToneList.prototype=Object.create(ToneList.prototype);ManagerToneList.prototype.constructor=ManagerToneList;ManagerToneList.prototype.makeItem=function(tone){var item=ToneList.prototype.makeItem.call(this,tone);item.querySelector('.desc').addEventListener('click',function(){if(!addToneState&&!shareState&&!isPaused){currentPlayingTone=tone;tonePlayer.setTone(tone,function(playing){item.dataset.playing=playing;createOptions();});}else{tonePlayer.stop();}});item.addEventListener("focus",function(){var self=this;focusItem=tone;createOptions();});return item;};navigator.mozL10n.once(function(){var promises=[];var type=null;var listParent=document.getElementById('list-parent');var headerTitle=document.getElementById('header-title');toneList=new ManagerToneList('title-'+launchType,listParent);switch(launchType){case'systemRingtones':type='ringtone';headerTitle.setAttribute('data-l10n-id','system-ringtones');createBuiltin(type);break;case'systemAlerts':type='alerttone';headerTitle.setAttribute('data-l10n-id','notice-alerts');createBuiltin(type);break;case'myRingtones':type='ringtone';headerTitle.setAttribute('data-l10n-id','my-ringtones');createCustome(type);break;default:break;}
function createBuiltin(toneType){promises.push(window.builtInRingtones.list(toneType).then(function(tones){toneList.add(tones);}));}
function createCustome(toneType){promises.push(window.customRingtones.list(toneType).then(function(tones){toneList.add(tones);}));}
Promise.all(promises).then(function(){document.querySelector('body').dataset.ready=true;checkToneListLength();createOptions();sendNavigationResetEvent('listReady');});});function checkToneListLength(){var hasNoTones=document.querySelector(".hasNoTones");hasNoTones.hidden=!(("myRingtones"===launchType)&&toneList&&(0===getToneListSize()));}
function getToneListSize(){return document.querySelector('#list-parent ul').childNodes.length;}
function sendNavigationResetEvent(name,detail){var event=document.createEvent('CustomEvent');event.initCustomEvent(name,false,true,detail);window.dispatchEvent(event);}
function createOptions(){var softkeyName=(tonePlayer.getPaused()||(focusItem!==currentPlayingTone))?'Play':'Stop';var playAction={name:softkeyName,l10nId:softkeyName.toLowerCase(),priority:2,method:function(){isPaused=softkeyName==='Stop';}};var params=null;switch(launchType){case'systemRingtones':case'systemAlerts':if(localStorage.getItem('isLowMemoryDevice')==='true'){params={menuClassName:'menu-button',header:{l10nId:'message'},items:[playAction]};}else{params={menuClassName:'menu-button',header:{l10nId:'message'},items:[playAction,{name:'Share',l10nId:'share',priority:3,method:showShareDialog}]};}
break;case'myRingtones':if(getToneListSize()>0){params={header:{l10nId:'options'},items:[{name:'Add',l10nId:'add',priority:1,method:addNewTone},playAction,{name:'Add',l10nId:'add-ringtone',priority:10,method:addNewTone},{name:'Share',l10nId:'share',priority:10,method:showShareDialog},{name:'Delete',l10nId:'delete',priority:10,method:fromListDeleteTone}]};}else{params={menuClassName:'menu-button',header:{l10nId:'message'},items:[{name:'Add',l10nId:'add',priority:1,method:addNewTone}]};}
break;default:break;}
if(option){option.initSoftKeyPanel(params);}else{option=new SoftkeyPanel(params);}
option.show();}});